name: master-cd

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          always-auth: true
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build bundle
        run: yarn docs

      - name: Upload bundle
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_PRD_HOST }}
          username: ${{ secrets.SSH_PRD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build"
          target: "~"

      - name: Upgrade apps
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo mv build docs
            sudo cp -rf docs /usr/
            sudo rm -rf docs
          host: ${{ secrets.SSH_PRD_HOST }}
          user: ${{ secrets.SSH_PRD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}